![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [30]:
import numpy as np
my_array = np.arange(0,10,1)
print(my_array)
print(my_array[9:0:-2])


[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [31]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [33]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [83]:
my_matrix=np.arange(1,21,1)
print(my_matrix)
print("-"*20)
my_matrix4x5=np.reshape(my_matrix,(4,5))
print(my_matrix4x5)
print("-"*20)
my_matrix5x4=np.reshape(my_matrix,(5,4))
print(my_matrix5x4)
print("-"*20)
invertida = my_matrix4x5[::-1, ::-1]
print(invertida)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
--------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
--------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
--------------------
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [140]:
my_matrix=np.arange(1,21,1)
print(my_matrix)
x=np.resize(my_matrix,(4,5))
print(x)
x[0:2, 0:2]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [149]:
my_matrix=np.arange(1,21,1)
print(my_matrix)
x=np.resize(my_matrix,(2,10))
print(x)
x[:,0:5:2]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [166]:
print(my_matrix)
x=np.resize(my_matrix,(3,5))
print(x)
x[0:3:1,::-1]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

filtro = (x=="Loro")
resultado=x[filtro]
print(resultado)

filtro2=np.where(x=="Loro")
print(x[filtro2])


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [197]:
my_secuence=np.arange(20)
print(my_secuence)
my_matrix=np.reshape(my_secuence,(2,5,2))
print(my_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [204]:
my_matrix=np.arange(1,21,1)
print(my_matrix)

x=np.resize(my_matrix,(4,5))
print(x)
x[::-1,::-1]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [229]:
mi_array=np.full(10,"O")
print(mi_array)
print((mi_array.nbytes))


['O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O' 'O']
40


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [236]:
vector=np.arange(10,50,1)
print(vector)
print(vector[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [246]:
vector=np.array([1,2,0,0,4,0])
filtro=np.where(vector!=0)
print(filtro)

(array([0, 1, 4]),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [258]:
import random
aleatorios=np.random.randint(10,size=(10,10))
print(aleatorios)
max=np.max(aleatorios)
print(f"Número máximo:= {max}")
min=np.min(aleatorios)
print(f"Número mínimo:= {min}")


[[4 3 2 3 3 0 8 1 3 9]
 [8 5 1 2 2 3 7 3 5 5]
 [9 7 3 3 5 0 3 9 8 2]
 [0 2 9 7 2 6 0 7 0 4]
 [3 3 5 3 0 0 2 0 5 0]
 [1 1 2 8 7 2 4 4 2 3]
 [8 7 8 7 8 8 6 9 2 0]
 [7 2 2 2 9 9 4 1 4 7]
 [4 8 8 3 6 6 9 4 8 0]
 [1 0 1 9 8 3 2 6 3 5]]
Número máximo:= 9
Número mínimo:= 0


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [282]:
vector_aleatorio=np.random.randint(0,100,size=30)
print((vector_aleatorio))
mean=np.mean(vector_aleatorio)
print(round(mean))


[97 77 81 20  1 93 18  5 90 84 43 15 53 17 66 43 50 42  8 31 21 60 77 68
 40 83 70  9 52 17]
48


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8